### ISSUE TITLE
Failed to load OrthographicCamera.svelte

### ISSUE THREAD

**Issue by tw1t611** [vatro/svelthree#37]
Hi, it might be cause of I am using svelte@next, but since they are switching to snowpack soon, this issue could be interesting to you.
`rollup-plugin-svelte` is installed (see package.json)

Even if you cannot resolve the issue for this svelte version. I would still be happy to get some feedback, or hints for a workaround.

Steps to reproducte:
1. npm init svelte@next
2. yarn
3. yarn add svelthree
4. Put the code into index.svelte

Code:
```js
  import { GLTFLoader } from "svelthree";
  const loader = new GLTFLoader();

  loader.load(
    "gltf/adamHead/adamHead.gltf",
    function (gltf) {
      scene.add(gltf.scene);
    },
    undefined,
    function (error) {
      console.error(error);
    }
  )
```
Error:
```bash
[snowpack] ! installing dependencies...
[snowpack] Failed to load node_modules/svelthree/src/components/OrthographicCamera.svelte
  Try installing rollup-plugin-svelte and adding it to Snowpack (https://www.snowpack.dev/#custom-rollup-plugins)
[snowpack] > Install failed.
[snowpack] Error: Install failed.
    at Object.install (/home/user/Projects/ari-motors-v2/node_modules/esinstall/src/index.ts:532:13)
    at Object.run (/home/user/Projects/ari-motors-v2/node_modules/snowpack/src/commands/install.ts:97:23)
    at installDependencies (/home/user/Projects/ari-motors-v2/node_modules/snowpack/src/sources/local.ts:24:25)
    at Object.prepare (/home/user/Projects/ari-motors-v2/node_modules/snowpack/src/sources/local.ts:81:29)
    at Object.startDevServer (/home/user/Projects/ari-motors-v2/node_modules/snowpack/src/commands/dev.ts:324:25)
    at Watcher.init_snowpack (/home/user/Projects/ari-motors-v2/node_modules/@sveltejs/kit/src/api/dev/index.js:109:19)
    at Watcher.init (/home/user/Projects/ari-motors-v2/node_modules/@sveltejs/kit/src/api/dev/index.js:55:3)
    at /home/user/Projects/ari-motors-v2/node_modules/@sveltejs/kit/src/cli.js:49:20
```

package.json:
```json
{
  "name": "ari-motors-v2",
  "version": "2.0.0",
  "license": "Unlicense",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "start": "svelte-kit start",
    "deploy": "cd strapi/ && gcloud builds submit",
    "dumpdb": "scripts/dumpdb.sh"
  },
  "devDependencies": {
    "@snowpack/plugin-postcss": "^1.0.11",
    "@sveltejs/adapter-node": "next",
    "@sveltejs/kit": "next",
    "@sveltejs/snowpack-config": "next",
    "autoprefixer": "^10.1.0",
    "cssnano": "^4.1.10",
    "cypress": "^6.3.0",
    "postcss": "^8.2.1",
    "postcss-cli": "^8.3.1",
    "postcss-load-config": "^3.0.0",
    "postcss-preset-env": "^6.7.0",
    "rollup-plugin-svelte": "^7.1.0",
    "svelte": "^3.29.0",
    "svelte-media": "^0.0.3",
    "svelte-preprocess": "^4.6.1",
    "svelthree": "^0.119.0-5",
    "tailwindcss": "^2.0.2"
  },
  "dependencies": {
    "@tailwindcss/forms": "^0.2.1",
    "marked": "^1.2.7",
    "svelte-i18n": "^3.3.0"
  }
}
```

snowpack.config.js
```js
module.exports = {
  extends: "@sveltejs/snowpack-config",
  plugins: [
    [
      "@snowpack/plugin-build-script",
      {
        cmd: "postcss",
        input: [".css", ".pcss"],
        output: [".css"],
      },
    ],
    [
      "@snowpack/plugin-svelte",
      {
        compilerOptions: {
          hydratable: true,
        },
      },
    ],
  ],
  mount: {
    "src/components": "/_components",
    "src/styles": "/_styles",
    "src/icons": "/_icons",
    "src/utils": "/_utils",
    "static/lang": "/lang",
  },
};
```

**Comment by vatro** [comment]
Hi! Thanks for the hint, I'm in the middle of a major refactor and was already planing to tackle (or maybe even switch to) snowpack for the next version, so I should be able to help you more soon.

Keep in mind that the current svelthree version is very early stage release, it's not advised to use it in production.

**Comment by tw1t611** [comment]
Hey, just FYI, they seem to switch to vite. 
So maybe we wait for some official statement, or release.
https://vitejs.dev/

**Comment by vatro** [comment]
thanks, yeah, I've stumbled over it on Twitter today, I think I'll better wait for the public SvelteKit beta <strike>before dumping Rollup 😉 + as always: whatever does the job best! 🚀🤷‍♂️ </strike>

EDIT: oh, Vite bundles with Rollup! Dumping nothing!

**Comment by vatro** [comment]
Closing this since SvelteKit uses Vite now.
